### ISSUE TITLE
Feature request: toggle mode

### ISSUE THREAD

**Issue by MistarMuffin** [bradgearon/hdr-switch#1]
This is great, thank you. I would love to make an AutoHotkey script to toggle HDR mode using this app. To that effect, I would love it if the app could determine the current HDR state, flip it the other way and then exit. That way you don't to leave the app running and minimize it. This would allow the app to be run each time the mode needs to be flipped. Perhaps a command line switch like hdr-switch --toggle or something similar?

Thanks.

**Comment by bradgearon** [comment]
Thanks! That sounds useful. I guess we'd have to figure out how to save the settings.

**Comment by Trilyan** [comment]
Even though I agree a "toggle" version would be awesome, I have done an AHK script to mimic what @MistarMuffin intends (as long as HDRSwitch.exe is on the same folder as the script):

#SingleInstance, Force
#NoEnv
#Warn
SetWorkingDir %A_ScriptDir%
HDR_ON := "HDRSwitch.exe"
Process, Exist, %HDR_ON%
IF ErrorLevel = 0 {Run, %HDR_ON%,,Hide}
ELSE{Process, Close, %HDR_ON%}

**Comment by bradgearon** [comment]
I made a toggle version... try this out - it is now just a windows tray app

**Comment by MistarMuffin** [comment]
Thank you!

**Comment by bradgearon** [comment]
I also added a toggle command to the app, but you have to be running the tray version and then you just call it like this while it is running to toggle:
```
hdr_switch_tray hdr
```

grab the latest version if you want to use that

**Comment by Trilyan** [comment]
Thank you Brad! Just tested it and it works great.

I'm trying to automate HDR setting before launching HDR apps

Is it possible to force HDR ON/OFF commands on CMD? That way it won't toggle OFF if it is already ON (it would remain ON)

Another route would be a command that outputs HDR current status (ON or OFF) and use that in a conditional.

**Comment by indeed-a-genius** [comment]
Could you add additional toggles? I'd like to switch to the "RGB 10 bit" option using command line.
