### ISSUE TITLE
Broken on Windows 1909

### ISSUE THREAD

**Issue by Pirateguybrush** [bradgearon/hdr-switch#3]
Great tool!  But since the 1909 update, this doesn't work for me any more.

**Comment by Trilyan** [comment]
Works for me on 1909 
![image](https://user-images.githubusercontent.com/7435782/82825675-07adf700-9e82-11ea-9685-c2a2b66efd76.png)

**Comment by bradgearon** [comment]
this might be a c++ library issue.. make sure you have the latest installed

[2019 x64 redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe)
[2019 x86 redistributable](https://aka.ms/vs/16/release/VC_redist.x86.exe)
